// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4d-eJYSW_PqdzLcoejFE5rAqPCKciFgc',
    appId: '1:194753042220:web:61af4a9187d6381815fe89',
    messagingSenderId: '194753042220',
    projectId: 'hostelmatesapp',
    authDomain: 'hostelmatesapp.firebaseapp.com',
    storageBucket: 'hostelmatesapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuiz9lsnqVOVPZ7weg_Wj0FqGqtskj5bY',
    appId: '1:194753042220:android:af90984ef83306b315fe89',
    messagingSenderId: '194753042220',
    projectId: 'hostelmatesapp',
    storageBucket: 'hostelmatesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9OB3ygHt_rjQtP8h3M916jt7_7BHD9c',
    appId: '1:194753042220:ios:f5fcd3c8b9ddec1315fe89',
    messagingSenderId: '194753042220',
    projectId: 'hostelmatesapp',
    storageBucket: 'hostelmatesapp.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9OB3ygHt_rjQtP8h3M916jt7_7BHD9c',
    appId: '1:194753042220:ios:f5fcd3c8b9ddec1315fe89',
    messagingSenderId: '194753042220',
    projectId: 'hostelmatesapp',
    storageBucket: 'hostelmatesapp.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4d-eJYSW_PqdzLcoejFE5rAqPCKciFgc',
    appId: '1:194753042220:web:922099d6289e405a15fe89',
    messagingSenderId: '194753042220',
    projectId: 'hostelmatesapp',
    authDomain: 'hostelmatesapp.firebaseapp.com',
    storageBucket: 'hostelmatesapp.firebasestorage.app',
  );
}
